spring.application.name=escala

# Perfil padrao (sobrescrito em prod pela variavel SPRING_PROFILES_ACTIVE)
spring.profiles.active=prod

# Porta padrao
server.port=${PORT:8080}
resend.api.key=${RESEND_API_KEY:}
resend.api.from=${RESEND_EMAIL_FROM:Hope Escala Pro <nao-responda@hopeescalapro.com.br>}

# Configuracoes de encoding
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
