# Configurações de Conexão com o Banco de Dados
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/escala-hope}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:123456}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do JPA / Hibernate para Produção
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Inicialização de Scripts SQL (Desativado em produção para evitar rodar scripts repetidos)
spring.sql.init.mode=never
spring.sql.init.encoding=UTF-8
spring.jpa.defer-datasource-initialization=false

# Porta do Servidor
server.port=${PORT:8090}

# Configurações do JWT
jwt.secret=${JWT_SECRET:HopeEscalaSistemaJWT2026MinhaChaveSuperSecretaComMaisDe32Caracteres}
jwt.expiration=${JWT_EXPIRATION:86400000}
