spring.profiles.active=test
 
jwt.secret=HopeEscalaSistemaJWT2026MinhaChaveSuperSecretaComMaisDe32Caracteres
jwt.expiration=86400000

logging.level.org.springframework.security=TRACE
 

#jwt.expiration=604800000
#jwt.secret=StringUsadaParaGerarToken
#jwt.expiration=600
#3376b06a-e45ec3d4-37cb-4e9e-895b-844f19e44ec6