spring.application.name=hope-escala-pro

# Ativa o perfil "dev" por padrão quando você der play localmente
spring.profiles.active=dev

# Fuso horário oficial do Brasil e formatação de datas
spring.jackson.time-zone=America/Sao_Paulo
spring.jackson.locale=pt_BR
spring.jackson.serialization.write-dates-as-timestamps=false

# Limite para upload de anexos e mídias
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100			MB

# Mensagens de erro nas respostas da API (sem expor o stacktrace completo)
server.error.include-stacktrace=never
server.error.include-message=always


 
jwt.secret=HopeEscalaSistemaJWT2026MinhaChaveSuperSecretaComMaisDe32Caracteres
jwt.expiration=86400000

logging.level.org.springframework.security=TRACE
 

#jwt.expiration=604800000
#jwt.secret=StringUsadaParaGerarToken
#jwt.expiration=600
#3376b06a-e45ec3d4-37cb-4e9e-895b-844f19e44ec6