server.port=8080

# Conexão PostgreSQL Local
spring.datasource.url=jdbc:postgresql://localhost:5432/escala-hope
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# Pool de conexões Hikari (Dev)
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2

# JPA / Hibernate Local (mostra o SQL formatado para facilitar debug)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Chave secreta de JWT para testes locais (mínimo 256 bits)
jwt.secret=ChaveDevMuitoSecretaHopeEscalaProComMaisDe256BitsParaAssinatura123456
jwt.expiration=86400000

# SMTP / E-mail de Desenvolvimento (pode apontar para Mailtrap ou deixar mockado)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=seu-email-dev@gmail.com
spring.mail.password=sua-senha-de-app
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
